### ISSUE TITLE
Plot timeline with track crossing international dateline

### ISSUE THREAD

**Issue by abfleishman** [benjamin-merkel/ProMM#5]
When I use `plot_timeline()` with data that cross the international dateline, there longitude panel does not work quite right (see below).  It would be nice to have an argument in the function to have it center on 180 instead of 0.  also, does this mean that there are issues else where with the way anything is being calculated?
![screen shot 2017-01-06 at 1 43 28 pm](https://cloud.githubusercontent.com/assets/9219852/21734079/72573984-d416-11e6-962a-80510743ccbe.png)

**Comment by benjamin-merkel** [comment]
Thank you for pointing out all these short comings in my script. As I am sure you noticed, I have not thought about issues relating to the pacific (like date line and crossing the 180 Longitude) mainly because I am working in the Atlantic. I will add an option to plot_timeline to center around 180. The script should work fine when crossing 180. I will have a look regarding your error message.
